// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZfMOlNhYmqvYeD1kcUyUzlX5RP9d2jV4',
    appId: '1:10493043228:android:6e204325762246c7ac35d9',
    messagingSenderId: '10493043228',
    projectId: 'employeefirebase-92003',
    storageBucket: 'employeefirebase-92003.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhB6EaoHqNsbyWaNA1CJGhSizTJWhKU1k',
    appId: '1:10493043228:ios:ec4e8dd6ca3b035eac35d9',
    messagingSenderId: '10493043228',
    projectId: 'employeefirebase-92003',
    storageBucket: 'employeefirebase-92003.firebasestorage.app',
    iosBundleId: 'com.example.firebaseFirebase',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2xjzsnqddt7d1nqDec0X5GRlOmvg8-SQ',
    appId: '1:10493043228:web:953699f81c8a6438ac35d9',
    messagingSenderId: '10493043228',
    projectId: 'employeefirebase-92003',
    authDomain: 'employeefirebase-92003.firebaseapp.com',
    storageBucket: 'employeefirebase-92003.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhB6EaoHqNsbyWaNA1CJGhSizTJWhKU1k',
    appId: '1:10493043228:ios:ec4e8dd6ca3b035eac35d9',
    messagingSenderId: '10493043228',
    projectId: 'employeefirebase-92003',
    storageBucket: 'employeefirebase-92003.firebasestorage.app',
    iosBundleId: 'com.example.firebaseFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2xjzsnqddt7d1nqDec0X5GRlOmvg8-SQ',
    appId: '1:10493043228:web:af0210c2f23ccc4eac35d9',
    messagingSenderId: '10493043228',
    projectId: 'employeefirebase-92003',
    authDomain: 'employeefirebase-92003.firebaseapp.com',
    storageBucket: 'employeefirebase-92003.firebasestorage.app',
  );

}